config/routes.rb
Rails.application.routes.draw do

  devise_for :users

resources :projects, only: [:index, :create, :update, :destroy] do
  resources :tasks, only: [:create, :update, :destroy]
end

root 'projects#index'

get '/projects/:project_id/tasks/:id/priority/:where' => 'tasks#priority', as:'priority'
put '/projects/:project_id/tasks/:id/deadline' => 'tasks#deadline', as:'deadline'
get '/projects/:project_id/tasks/:id/done' => 'tasks#done', as:'done'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  belongs_to :user
  validates :title, presence: true
  validates :user, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  validates :text, presence: true
  validates :project, presence: true
  
  def local_time
    if self.deadline
      self.deadline.to_s(:long)
    else
      'No deadline set'
    end 
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  respond_to :html, :json, :js
  def index
    @projects = current_user.projects.all
  end

  def create
    @project = Project.new
    @project.title = 'New Project'
    @project.user = current_user
    if @project.save
      flash[:notice] = 'Project was successufully created'
      respond_with @project
    else
      redirect_to projects_path
    end
    
  end

  def update
    @project = Project.find(params[:id])
    if @project.user == current_user
      @project.title = params[:project][:title]
      if @project.save
        flash[:notice] = 'Project was successufully updated'
      end
    end
    respond_with @project
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.user == current_user
      if @project.destroy
        flash[:notice] = 'Project was successufully deleted'
      end
      respond_with @project
    else
      redirect_to projects_path
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  respond_to :html, :json, :js
  before_action :find_project, only: [:create, :destroy, :priority, :deadline] 
  before_action :find_task, only: [:update, :destroy, :priority, :deadline, :done]
  before_action :access

  def find_project
    @project = Project.find(params[:project_id])
  end
  
  def find_task
    @task = Task.find(params[:id])
  end

  def access
    unless Project.find(params[:project_id]).user == current_user
      flash[:notice] = 'Unrecognized user'
      redirect_to projects_path
    end
  end


  def create    
    @task = @project.tasks.new
    @task.text = params[:task][:text]
    @task.is_done = false
    @task.priority = @project.tasks.count+1
    if @task.save
      flash[:notice] = 'Task was successufully created'
      respond_with @project
    else 
      redirect_to projects_path
    end
  end

  def update
    @task.text = params[:task][:text]
    if @task.save
      flash[:notice] = 'Task was successufully updated'
      respond_with @task
    else
      redirect_to projects_path
    end
  end

  def destroy
    @priority_destroy = @task.priority
    if @task.destroy
      @tasks = @project.tasks.where("priority > ?", @priority_destroy)
      @tasks.each do |t|
        t.priority -= 1
        t.save
      end
      flash[:notice] = 'Task was successufully deleted'
      respond_with @task
    else
      redirect_to projects_path
    end
  end

  def priority
    if params[:where] == 'up'
      @priority = @task.priority
      unless @priority == 1
        @task_up = @project.tasks.where(priority: @priority-1).take
        @task.priority -= 1
        @task_up.priority += 1
        if @task.save
          flash[:priority_down] = 'Success'
        end
        if @task_up.save
          flash[:priority_up] = 'Success'
        end
      end
    end
    if params[:where] == 'down'
      @priority = @task.priority
      unless @priority == @project.tasks.count
        @task_down = @project.tasks.where(priority: @priority+1).take
        @task.priority += 1
        @task_down.priority -= 1
        if @task.save
          flash[:priority_up] = 'Success'
        end
        if @task_down.save
          flash[:priority_down] = 'Success'
        end
      end
    end
    redirect_to projects_path
  end

  def deadline
    @task.deadline = params[:task][:deadline]
    if @task.save
      flash[:notice] = 'Deadline was successufully updated'
      respond_with(@project,@task)
    else
      redirect_to projects_path
    end
  end

  def done
    @task.is_done = true
    if @task.save
      flash[:notice] = 'Task is done'
      respond_with @task
    else
      redirect_to projects_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tdl" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="container">
        <div class="row">
        <div class="span2">
        </div>
          <div class="span8">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span2">
          

          </div>
        </div><!--/row-->

      

    </div> <!-- /container -->

  </body>
</html>

app/views/projects/_project_top.html.erb
<div class="project-header">
  <div class="project-title">
  <i class="icon-cogs icon-silver icon-my icon-large"></i><span  id='project_name<%=project.id%>'><%= best_in_place project, :title %></span>
  
    <%= link_to content_tag(:i, '', class: "icon-trash icon-large icon-silver pull-right"), project_path(project),
                    method: :delete, data: { confirm: 'Are you sure?' }, :remote=>true, :class=>"delete_project" %>
    </div>

    </div>
    <div class="new-task">
    <i class="icon-plus icon-2x icon-green icon-my"></i>
   <%= form_for [project, Task.new], :html=> {:style=>"display: inline;",:class=>"form-inline create_task" },:remote=>true do |f| %>
    <%= f.text_field :text, :placeholder=>"Start typing here to create a task...", :class=>"span6 new_task", id:"new_task_#{project.id}" %>
    <%= f.submit  'New Task', class:"btn btn-success", id:"new_btn_#{project.id}", disabled:"disabled"%>
    <% end %>
    
    </div>

app/views/projects/create.html.erb
<h1>Projects#create,update</h1>
<p>Find me in app/views/projects/create,update.html.erb</p>

app/views/projects/create.js.erb
$('.create_project').before('<div class="project_top"><%= escape_javascript(render partial:"project_top", locals: {project:@project})%></div><div class="tasks"></div>');

app/views/projects/destroy.js.erb
$('.delete_project').bind('ajax:success', function() {
    $(this).parent().parent().parent().next().remove();
    $(this).parent().parent().parent().remove(); //project_top remove
});  

app/views/projects/index.html.erb
<% @projects.each do |project| %>

<div class="project_top">
<%= render partial: 'project_top',locals: {project:project} %>
</div>
  
    <div class="tasks">  
<%= render partial: 'tasks/tasks', locals: {project:project}%>
  </div>
<% end %>

<%= form_for Project.new , method: :post, :remote=>true, :html=> {:style=>"display: inline;",:class=>"form-inline create_project",:attr=>'data-no-turbolink' } do |f| %>

  <div align="center" style="margin-top:30px;">
  <%= button_tag(type: 'submit', class: "btn btn-primary btn-large") do %>
  <i class="icon-plus icon-large"></i> New Project
  <% end %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
   <% if task.priority == project.tasks.count %>
<div class="task last-task">
<% else %>
<div class="task">
   <% end %>
   <% if task.is_done %>
    <i class="icon-check icon-large icon-my pull-left" style="
    padding-top: 15px;"></i>
    <% else %>
    <%= link_to content_tag(:i, '', class: "icon-check-empty icon-large icon-my pull-left",style:"padding-top:15px;width: 18px;"), done_path(project,task), data: { confirm: 'Are you sure?' } %>
    <% end %>
   <div class="span3 task-title">
    <span id='task_name<%=task.id%>'><%= best_in_place task, :text ,:path=>project_task_path(project,task)%></span>
    </div>
    


<div class="task-right" id="task-right">
<img src="<%= asset_path('sort.png') %>" usemap="#sort<%= task.id%>">
<map name="sort<%= task.id%>">
<area shape="rect" coords="0,0,16,8" href="<%= priority_path(project,task,'up')%>" title="UP" alt="UP" />
<area shape="rect" coords="0,8,16,16" href="<%= priority_path(project,task,'down')%>" title="DOWN" alt="DOWN" />
</map>
    <%= link_to content_tag(:i, '', class: "icon-trash icon-large icon-my "), project_task_path(project,task), method: :delete, data: { confirm: 'Are you sure?' }, :remote=>true, :class=>"delete_task"  %>

<div class="task-deadline">
<% if task.is_done %>
<span>
Task is Done
    <% else %>
<span id="task_dl<%=task.id%>">
    <%= best_in_place task, :deadline, :place_holder=>"No deadline set", :path=>deadline_path(project,task), :type => :datetime, :display_as=>'local_time'  %>    
    <% end%>
    </span>
  </div>
  </div>
    </div>

app/views/tasks/_tasks.html.erb
  <% project.tasks.order('priority').each do |task| %>
   <% if task.priority == project.tasks.count %>
<div class="task last-task">
<% else %>
<div class="task">
   <% end %>
   <% if task.is_done %>
    <i class="icon-check icon-large icon-my pull-left" style="
    padding-top: 15px;"></i>
    <% else %>
    <%= link_to content_tag(:i, '', class: "icon-check-empty icon-large icon-my pull-left",style:"padding-top:15px;width: 18px;"), done_path(project,task),:remote=>true,:class=>'mark_as_done', data: { confirm: 'Are you sure?' } %>
    <% end %>
   <div class="span3 task-title">
    <span id='task_name<%=task.id%>'><%= best_in_place task, :text ,:path=>project_task_path(project,task)%></span>
    </div>
    


<div class="task-right" id="task-right">
<img src="<%= asset_path('sort.png') %>" usemap="#sort<%= task.id%>">
<map name="sort<%= task.id%>" >
<area shape="rect" coords="0,0,16,8" href="<%= priority_path(project,task,'up')%>"  title="UP" alt="UP" />
<area shape="rect" coords="0,8,16,16" href="<%= priority_path(project,task,'down')%>" title="DOWN" alt="DOWN" />
</map>
    <%= link_to content_tag(:i, '', class: "icon-trash icon-large icon-my "), project_task_path(project,task), method: :delete, data: { confirm: 'Are you sure?' }, :remote=>true, :class=>"delete_task"  %>

<div class="task-deadline">
<% if task.is_done %>
<span>
Task is Done
    <% else %>
<span>
    <%= best_in_place task, :deadline, :path=>deadline_path(project,task), :type => :datetime, :display_as=>'local_time'  %>  
    <% end%>
    </span>
  </div>
  </div>
    </div>
     <% end %>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/create.js.erb
$('.create_task').bind('ajax:success', function() {
    $(this).parent().parent().next().html("<%= escape_javascript(render partial:'tasks/tasks', locals: {project:@project})%>");
    $(this[1]).val('');
    $(this[2]).attr('disabled','true');
});

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/destroy.js.erb
$('.delete_task').bind('ajax:success', function() {
    var to_delete = $(this).parent().parent();
    if(to_delete.hasClass('last-task') && to_delete.prev().hasClass('task')){
        to_delete.prev().addClass('last-task');
    }
    to_delete.remove();
});  

app/views/tasks/done.js.erb
$('.mark_as_done').bind('ajax:success', function() {
    var dl = $(this).next().next().children()[3];
    $(dl).replaceWith('<div class="task-deadline"><span>Task is Done</span></div>');
    $(this).replaceWith('<i class="icon-check icon-large icon-my pull-left" style="padding-top: 15px;"></i>');
}); 

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>